version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: redaction-backend
    environment:
      - FLASK_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: redaction-frontend
    environment:
      - VITE_API_URL=http://backend:5000/api
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
